name: depoly

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: "Install Dependency"
        run: yarn install

      - uses: cloudflare/wrangler-action@1.3.0
        name: "Publish"
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
