name: depoly

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: "Install Dependency"
        run: yarn install

      - name: "Install wrangler"
        run: yarn global add @cloudflare/wrangler

      - name: "Publish"
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish
